//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum LogLevelEnum {
	Trace = 0,
	Debug = 1,
	Information = 2,
	Warning = 3,
	Error = 4,
	Critical = 5,
	None = 6
}
export enum HistoryDataIntervalEnum {
	One_Minute = 0,
	Two_Minutes = 1,
	Five_Minutes = 2,
	Fifteen_Minutes = 3,
	Thirty_Minutes = 4,
	Sixty_Minutes = 5,
	Ninety_Minutes = 6,
	One_Day = 7,
	Five_Days = 8,
	One_Week = 9,
	One_Month = 10,
	Three_Months = 11
}
export enum DelistEnum {
	Nasdaq_Removed = 0,
	Yfinance_No_Ticker = 1,
	Yfinance_No_Info = 2,
	Yfinance_No_History = 3
}
export enum SentimentEnum {
	Negative = 0,
	Neutral = 1,
	Positive = 2
}
export enum SentimentResultTypeEnum {
	NewsArticle = 0
}
export enum SentimentStatusEnum {
	Pending = 0,
	Queued = 1,
	Completed = 2,
	Failed = 3
}
