//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { HistoryDataIntervalEnum } from './model.enum';
import { DelistEnum } from './model.enum';
import { LogLevelEnum } from './model.enum';
import { CronLogTypeEnum } from './model.enum';
import { SentimentResultTypeEnum } from './model.enum';
import { SentimentStatusEnum } from './model.enum';
import { SentimentEnum } from './model.enum';

export interface IPaginate
{
	pageIndex: number;
	pageItemCount: number;
	totalPages: number;
	totalItemCount: number;
}
export interface IPaginateGeneric<T>
{
	items: T[];
	pageIndex: number;
	pageItemCount: number;
	totalPages: number;
	totalItemCount: number;
}
export interface IPaginateGenericFilter<T>
{
	filter: T;
	pageIndex: number;
	pageItemCount: number;
	orderBy?: string;
	isOrderAsc: boolean;
	isPaginated: boolean;
}
export interface IDropDown
{
	id: number;
	name: string;
}
export interface IPaginateFilter
{
	pageIndex: number;
	pageItemCount: number;
	orderBy?: string;
	isOrderAsc: boolean;
	isPaginated: boolean;
}
export interface IStringData
{
	data: string;
}
export interface IWatchTickerChange
{
	tickerIds: number[];
	updateHistoryData: boolean;
	updateNewsArticles: boolean;
}
export interface IWatchTickerDetailsChange
{
	updateHistoryData: boolean;
	updateNewsArticles: boolean;
	filter: any;
}
export interface IWatchTicker
{
	updateHistoryData: boolean;
	updateNewsArticles: boolean;
	id: number;
}
export interface IWatchTickerResult
{
	updatedCount: number;
	removedCount: number;
	addedCount: number;
	currentCount: number;
	maxCount: number;
}
export interface IWatchUserStatus
{
	watchTicerCount: number;
	watchTickerCountMax: number;
}
export interface IClientToken
{
	userId: number;
	userName: string;
	exp: Date;
	iat: Date;
	nbf: Date;
	roles: string[];
}
export interface ILogin
{
	userName: string;
	password: string;
}
export interface INewsArticle
{
	title: string;
	link: string;
	text: string;
	articleDate: Date;
	sentimentResults: ISentimentResult[];
	id: number;
}
export interface INewsFilter
{
	symbol?: string;
	minDate?: Date;
	maxDate?: Date;
}
export interface IHistoryData
{
	tickerId: number;
	interval: HistoryDataIntervalEnum;
	open: number;
	close: number;
	high: number;
	low: number;
	volume: number;
	date: Date;
	id: number;
}
export interface IMarketSchedule
{
	date: Date;
	marketOpenDateTime: Date;
	marketCloseDateTime: Date;
	id: number;
}
export interface ITickerDelistReason
{
	tickerId: number;
	delist: DelistEnum;
	createdDate: Date;
	id: number;
}
export interface ITicker
{
	symbol: string;
	lastHistoryUpdateDateTime?: Date;
	lastInfoUpdateDateTime?: Date;
	lastNewsUpdateDateTime?: Date;
	name: string;
	quoteType: string;
	exchange: string;
	marketCap?: number;
	sector?: string;
	industry?: string;
	volume?: number;
	payoutRatio?: number;
	dividendRate?: number;
	delistReasons: ITickerDelistReason[];
	watchTickers: IWatchTicker[];
	id: number;
}
export interface ITickerFilter
{
	name?: string;
	symbol?: string;
	quoteType?: string;
	sector?: string;
	industry?: string;
	isListed?: boolean;
	isUserWatching?: boolean;
}
export interface ITickerHistorySummary
{
	valueSummaries: IValueSummary[];
}
export interface IValueSummary
{
	title: string;
	date?: Date;
	value?: number;
	difference?: number;
}
export interface IAppLog
{
	logLevel: LogLevelEnum;
	eventId: number;
	eventName?: string;
	source?: string;
	stackTrace?: string;
	message: string;
	createdDateTime: Date;
}
export interface IAppLogFilter
{
	logLevel?: LogLevelEnum;
	eventId?: number;
	eventName?: string;
	minDate?: Date;
	maxDate?: Date;
}
export interface ICronLog
{
	id: number;
	name: string;
	cronLogType: CronLogTypeEnum;
	message?: string;
	isCanceled: boolean;
	startDateTime: Date;
	endDateTime: Date;
}
export interface ICronLogFilter
{
	name?: string;
	cronLogType?: CronLogTypeEnum;
	isCanceled?: boolean;
	minDate?: Date;
	maxDate?: Date;
}
export interface IPythonLog
{
	file: string;
	output?: string;
	error?: string;
	startDateTime: Date;
	endDateTime: Date;
}
export interface IPythonLogFilter
{
	file?: string;
	hasError?: boolean;
	minDate?: Date;
	maxDate?: Date;
}
export interface ICronJobDetail
{
	name: string;
	cronExpression: string;
	nextOccurrence?: Date;
	lastOccurrence?: Date;
	isRunning: boolean;
}
export interface ICronQueueDetail
{
	name: string;
	isRunning: boolean;
	isPendingStop: boolean;
}
export interface IAppUser
{
}
export interface IToken
{
	accessToken: string;
	refreshToken: string;
}
export interface IHuggingFaceModel
{
	name: string;
	isDefault: boolean;
	id: number;
}
export interface IQueueSentiment
{
	huggingFaceModelId: number;
	sentimentResultType: SentimentResultTypeEnum;
	itemIds: number[];
}
export interface ISentimentResult
{
	huggingFaceModelId: number;
	newsArticleId?: number;
	negative: number;
	neutral: number;
	positive: number;
	status: SentimentStatusEnum;
	huggingFaceModel: IHuggingFaceModel;
	newsArticle: INewsArticle;
	sentimentResultType: SentimentResultTypeEnum;
	sentiment: SentimentEnum;
	createdDate: Date;
	updatedDate?: Date;
	id: number;
}
