//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface IEntityDto
{
	id?: number;
}
export interface IEntityAuditCreateDto extends IEntityDto
{
	createdDate?: Date;
}
export interface IEntityUserAuditCreateDto extends IEntityAuditCreateDto
{
	createdByAppUserId?: number;
	createdBy?: IAppUserDto;
}
export interface IEntityAuditUpdateDto extends IEntityDto
{
	updatedDate?: Date;
}
export interface IEntityUserAuditUpdateDto extends IEntityAuditUpdateDto
{
	updatedByAppUserId?: number;
	updatedBy?: IAppUserDto;
}
export interface IEntityAuditRemoveDto extends IEntityDto
{
	removedDate?: Date;
}
export interface IEntityUserAuditRemoveDto extends IEntityAuditRemoveDto
{
	removedByAppUserId?: number;
	removedBy?: IAppUserDto;
}
export interface IEntityAuditCreateUpdateDto extends IEntityDto
{
	createdDate?: Date;
	updatedDate?: Date;
}
export interface IEntityUserAuditCreateUpdateDto extends IEntityAuditCreateUpdateDto
{
	createdByAppUserId?: number;
	updatedByAppUserId?: number;
	createdBy?: IAppUserDto;
	updatedBy?: IAppUserDto;
}
export interface IEntityAuditCreateRemoveDto extends IEntityDto
{
	createdDate?: Date;
	removedDate?: Date;
}
export interface IEntityUserAuditCreateRemoveDto extends IEntityAuditCreateRemoveDto
{
	createdByAppUserId?: number;
	removedByAppUserId?: number;
	createdBy?: IAppUserDto;
	removedBy?: IAppUserDto;
}
export interface IEntityAuditUpdateRemoveDto extends IEntityDto
{
	updatedDate?: Date;
	removedDate?: Date;
}
export interface IEntityUserAuditUpdateRemoveDto extends IEntityAuditUpdateRemoveDto
{
	updatedByAppUserId?: number;
	removedByAppUserId?: number;
	updatedBy?: IAppUserDto;
	removedBy?: IAppUserDto;
}
export interface IEntityAuditCreateUpdateRemoveDto extends IEntityDto
{
	createdDate?: Date;
	updatedDate?: Date;
	removedDate?: Date;
}
export interface IEntityUserAuditCreateUpdateRemoveDto extends IEntityAuditCreateUpdateRemoveDto
{
	createdByAppUserId?: number;
	updatedByAppUserId?: number;
	removedByAppUserId?: number;
	createdBy?: IAppUserDto;
	updatedBy?: IAppUserDto;
	removedBy?: IAppUserDto;
}
export interface IPaginateDto<T>
{
	pageIndex?: number;
	pageItemCount?: number;
	totalPages?: number;
	totalItemCount?: number;
	items?: T[];
}
export interface IPaginateFilterDto
{
	pageIndex?: number;
	pageItemCount?: number;
	orderBy?: string;
	isOrderAsc?: boolean;
	isPaginated?: boolean;
}
export interface IStringDataDto
{
	data?: string;
}
export interface IClientTokenDto
{
	userId?: number;
	userName?: string;
	exp?: Date;
	iat?: Date;
	nbf?: Date;
	roles?: string[];
}
export interface ILoginDto
{
	userName?: string;
	password?: string;
}
export interface IHistoryDataDto extends IEntityDto
{
	tickerId?: number;
	interval?: HistoryDataIntervalEnum;
	open?: number;
	close?: number;
	high?: number;
	low?: number;
	volume?: number;
	dateTime?: Date;
}
export interface ITickerDto extends IEntityDto
{
	symbol?: string;
	isDelisted?: boolean;
}
export interface IAppLogDto
{
	logLevel?: LogLevel;
	eventId?: number;
	eventName?: string;
	source?: string;
	stackTrace?: string;
	message?: string;
	createdDate?: Date;
}
export interface ICronLogDto
{
	id?: number;
	name?: string;
	message?: string;
	isCanceled?: boolean;
	startDate?: Date;
	endDate?: Date;
}
export interface IPythonLogDto
{
	file?: string;
	output?: string;
	error?: string;
	startDate?: Date;
	endDate?: Date;
}
export interface IAppUserDto
{
}
export enum LogLevel {
	Trace = 0,
	Debug = 1,
	Information = 2,
	Warning = 3,
	Error = 4,
	Critical = 5,
	None = 6
}
export enum HistoryDataIntervalEnum {
	One_Minute = 0,
	Two_Minutes = 1,
	Five_Minutes = 2,
	Fifteen_Minutes = 3,
	Thirty_Minutes = 4,
	Sixty_Minutes = 5,
	Ninety_Minutes = 6,
	One_Day = 7,
	Five_Days = 8,
	One_Week = 9,
	One_Month = 10,
	Three_Months = 11
}
